inp_paragraph_file: '../BERT_cs/WIKI_C4Cleaned.txt'
out_sentence_file: '../BERT_cs/WIKI_C4Cleaned.sentences.norm2.txt'
not_supported_chars_file: './not_supported_chars2.txt'
ttstool_bin: './tts_tool/tts_tool'
ttstool_data: './tts_tool/data/frontend_normalize.json'
chunk_size: 4       # number of paragraphs processed by a single CPU
batch_size: 1000    # # number of sentences to write in once

supported_chars:
    lower_chars: 'aáäbcčdďeéěfghiíjklmnňoóöpqrřsštťuúůüvwxyýzž'
    upper_chars: 'AÁÄBCČDĎEÉĚFGHIÍJKLMNŇOÓÖPQRŘSŠTŤUÚŮÜVWXYÝZŽ'
    digits: '0123456789'
    whites_spaces: ' '
    punct: '.,;:-?'

replacements:
    character:
        '–': '-'
        '—': '-'
        '−': '-'
        # '"': ''
        # "'": ''
        # "„": ''
        # "“": ''
    paragraph:
        'km/h': 'kilometrů za hodinu'
        'm/s': 'metrů za sekundu'
        'př.n.l.': 'před naším letopočtem'
        'př. n. l.': 'před naším letopočtem'
        'st. př. Kr.': 'století před Kristem'
        'st. př. kr.': 'století před Kristem'
